"""
Django settings for kemsoft project.

Generated by 'django-admin startproject' using Django 3.1.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
#BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'm$@ei6!t1x(0(11*vmxq&w3nb12=xv&ynki7h-jqb%ew^o1qez'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG com valor True = modo desenvolvimento
# DEBUG com valor False = modo produção
DEBUG = False

ALLOWED_HOSTS = ['*'] # https://kemsoft-kem.herokuapp.com/


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'escola',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kemsoft.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kemsoft.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        #'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Maceio'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/' # usado durante o desenvolvimento.
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') # usando durante a produção.


LOGOUT_REDIRECT_URL = 'index'



# Usando Jazzmin

JAZZMIN_SETTINGS = {
    
   
   
    # Tela dando boas vindas e colocando a mensagem que desejar.
    "welcome_sign": "Bem vindo a KemSoftware",
    
    # Tela de boas vindas do Django
    "site_header": "KemSofware",

    # Tela do rodapé da aplicação informando o copyrigth.
    "copyright": "KemSoftware Ltd",


    # Testando Menus

    "topmenu_links": [        

        # external url that opens in a new window (Permissions can be added)
        #{"name": "Suporte", "url": "Whatsapp 82 98851-6305", "new_window": True},      
         {"name": "Contact/Whatsapp 82 98851-6305", "url": "", "new_window": True},  
    ],

    
    "show_sidebar": True,
    "navigation_expanded": True,
    
    # Não sei oque faz ainda.
    "changeform_format": "horizontal_tabs",
    
    
    # Deixar o Menu do Admin/usuario vertical ou horizontal
    "changeform_format_overrides": {"auth.user": "vertical_tabs", "auth.group": "vertical_tabs"},
    

    # Colocar Menu no canto superior direito para o usuario.
    "usermenu_links": [
        {"model": "auth.user"},
        {"name": "Suporte Contato", "url": "https://www.instagram.com/kemuelkesley/", "new_window": True},
        {"name": "Github", "url": "https://github.com/kemuelkesley", "new_window": True},
        #{"model": "auth.user"},       
    ],

    # Mudando icones do lado esquerdo
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        
    },
    

}

# Tema usado Simplex, mais pode acrescentar vários TEMAS.

JAZZMIN_UI_TWEAKS = {
    
    #"theme": "simplex",
    #"dark_mode_theme": "darkly",
    "theme":"lumen",
}

# Ativar os botões de edição no canto superior direito da tela.

JAZZMIN_SETTINGS["show_ui_builder"] = True
