# Generated by Django 3.2.3 on 2021-05-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
