# Generated by Django 3.2.3 on 2021-05-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_turma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='turma',
        ),
        migrations.AddField(
            model_name='aluno',
            name='bairro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cidade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
