# Generated by Django 3.2.3 on 2021-05-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_auto_20210520_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='numero',
            field=models.IntegerField(default=0, verbose_name='Número'),
        ),
    ]
