# Generated by Django 3.2.3 on 2021-05-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0005_aluno_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='nome',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
