# Generated by Django 3.2.3 on 2021-05-20 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0006_turma_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='Turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='escola.turma'),
        ),
    ]
