# Generated by Django 3.2.3 on 2021-05-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0008_aluno_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='bairro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cidade',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome'),
        ),
    ]
