# Generated by Django 3.2.3 on 2021-05-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0009_auto_20210521_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='idade',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
    ]
