# Generated by Django 3.2.3 on 2021-05-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0010_auto_20210521_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='idade',
        ),
    ]
