# Generated by Django 3.2.3 on 2021-05-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0012_geral_escolha_informacoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geral',
            name='escolha_informacoes',
        ),
        migrations.AddField(
            model_name='geral',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2),
        ),
    ]
