# Generated by Django 3.2.3 on 2021-05-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0013_auto_20210521_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_livro', models.CharField(blank=True, max_length=60, null=True, verbose_name='Nome do Livro')),
            ],
        ),
        migrations.DeleteModel(
            name='Geral',
        ),
    ]
