# Generated by Django 3.2.3 on 2021-05-23 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0014_auto_20210521_1331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Livro',
            new_name='Biblioteca',
        ),
    ]
