# Generated by Django 3.2.3 on 2021-05-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0015_rename_livro_biblioteca'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteca',
            name='autor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Autor'),
        ),
    ]
