# Generated by Django 3.2.3 on 2021-05-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0016_biblioteca_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteca',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
    ]
