# Generated by Django 3.2.3 on 2021-05-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0019_auto_20210523_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteca',
            name='autor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Autor'),
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descição  do Livro'),
        ),
    ]
