# Generated by Django 3.2.3 on 2021-05-24 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0022_auto_20210523_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biblioteca',
            name='Aluno',
        ),
        migrations.RemoveField(
            model_name='biblioteca',
            name='Turma',
        ),
        migrations.RemoveField(
            model_name='biblioteca',
            name='data_entrega',
        ),
        migrations.RemoveField(
            model_name='biblioteca',
            name='data_saida',
        ),
        migrations.RemoveField(
            model_name='biblioteca',
            name='descricao',
        ),
        migrations.CreateModel(
            name='SaidaDeLivro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='escola.aluno')),
                ('Biblioteca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='escola.biblioteca')),
            ],
        ),
    ]
