# Generated by Django 3.2.3 on 2021-05-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0023_auto_20210523_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='saidadelivro',
            name='entrega',
            field=models.DateField(null=True, verbose_name='Data de Entrega'),
        ),
        migrations.AddField(
            model_name='saidadelivro',
            name='saida',
            field=models.DateField(null=True, verbose_name='Data de Saida'),
        ),
    ]
