# Generated by Django 3.2.3 on 2021-05-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0024_auto_20210523_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='saidadelivro',
            name='atendente',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Atendente'),
        ),
    ]
