# Generated by Django 3.2.3 on 2021-05-24 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0025_saidadelivro_atendente'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteca',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Livro'),
        ),
    ]
