# Generated by Django 3.2.3 on 2021-05-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0026_biblioteca_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Livro')),
                ('autor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Autor')),
                ('descricao', models.TextField(verbose_name='Descrição')),
            ],
        ),
    ]
