# Generated by Django 3.2.3 on 2021-05-25 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0028_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Livro',
            name='autor',
        ),
    ]
