# Generated by Django 3.2.3 on 2021-05-25 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0032_auto_20210525_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='itembiblioteca',
            name='biblioteca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='escola.biblioteca'),
        ),
    ]
