# Generated by Django 3.2.3 on 2021-05-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0034_itembiblioteca_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biblioteca',
            name='nome_do_livro',
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='nome',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
