# Generated by Django 3.2.3 on 2021-05-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0036_remove_biblioteca_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblioteca',
            name='nome',
            field=models.CharField(default='biblioteca central', max_length=60),
        ),
    ]
