# Generated by Django 3.2.3 on 2021-05-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0037_alter_biblioteca_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name_plural': 'Autor'},
        ),
        migrations.AlterField(
            model_name='livro',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
