# Generated by Django 3.2.3 on 2021-05-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0038_auto_20210525_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='livro_autor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='descricao',
            field=models.TextField(verbose_name='Descrição do Livro'),
        ),
    ]
