# Generated by Django 3.2.4 on 2021-06-23 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0039_auto_20210525_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_atendente', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='itembiblioteca',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='autor',
            name='livro_autor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Livro'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='escola.autor', verbose_name='Autor'),
        ),
    ]
