# Generated by Django 3.2.4 on 2021-06-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0040_auto_20210623_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saidadelivro',
            name='atendente',
        ),
        migrations.AlterField(
            model_name='atendente',
            name='nome_atendente',
            field=models.CharField(max_length=50, verbose_name='Nome do Atendente'),
        ),
    ]
