# Generated by Django 3.2.4 on 2021-06-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0043_auto_20210623_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=models.CharField(blank=True, default='Juntos', max_length=11, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='rg',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='RG'),
        ),
    ]
